---
version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=33
      - TZ=America/Indianapolis
    volumes:
      - /home/justincampbell/Sync/config:/config
      - /home/justincampbell/Sync/downloads:/downloads
      - /home/justincampbell/Sync/:/sync
      - /var/www/html/:/sync/website
    ports:
      # WebUI Port
      - 9999:8888
      # Listening Port for BitTorrent Comms
      - 55555:55555
    restart: unless-stopped
